CREATE TABLE PROJECT(
PROJ# INT UNIQUE,
P_NAME VARCHAR(20),
P_DESC VARCHAR2(29),
P_BUDGET DECIMAL
);
CREATE TABLE WORKORDERS(
WO# INT UNIQUE,
PROJ# UNIQUE,
WO_DESC VARCHAR2(29) NOT NULL,
WO_ASSIGNED VARCHAR2(20)NOT NULL,
WO_HOURS DECIMAL CHECK (WO_HOURS>0),
WO_START TIMESTAMP,
WO_DUE TIMESTAMP,
WO_COMPLETE CHAR(1) CHECK (WO_COMPLETE IN ('Y','N'))
);
